WebKR_Schmelev/Pages/About.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebKR_Schmelev.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebKR_Schmelev/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace WebKR_Schmelev.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebKR_Schmelev/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace WebKR_Schmelev.Pages
{
    public class IndexModel : PageModel
    {
        private readonly postgresContext _postgresContext;
        private readonly mssqlContext _mssqlContext;

        public Dictionary<int, TimeSpan> TimesPostgres { get; set; }
        public Dictionary<int, TimeSpan> TimesMSSql { get; set; }

        public IndexModel(postgresContext dbPostgres, mssqlContext dbMSSql)
        {
            _postgresContext = dbPostgres;
            _mssqlContext = dbMSSql;
        }

        public void OnPostExecuteTest()
        {
            TimesPostgres = GetTimesOfWritingLargeObjects_Postgres();
            TimesMSSql = GetTimesOfWritingLargeObjects_MSSql();
        }

        public void OnGet()
        {
        }

        private Dictionary<int, TimeSpan> GetTimesOfWritingLargeObjects_Postgres()
        {
            Dictionary<int, TimeSpan> outputTimes = new Dictionary<int, TimeSpan>();
            for (int i = 1000; i < 1000000000; i *= 10)
            {
                String testString = get_unique_string(i);
                Stopwatch stopwatch = new Stopwatch();
                Test test = new Test { Test1 = DateTime.Now.ToString("dd.MM.yyyy hh:mm:ss:fff"), Test2 = testString };

                stopwatch.Start();
                _postgresContext.Tests.Add(test);
                _postgresContext.SaveChanges();
                stopwatch.Stop();

                outputTimes.Add(Encoding.UTF8.GetByteCount(testString), stopwatch.Elapsed);
            }
            return outputTimes;
        }

        private Dictionary<int, TimeSpan> GetTimesOfWritingLargeObjects_MSSql()
        {
            Dictionary<int, TimeSpan> outputTimes = new Dictionary<int, TimeSpan>();
            for (int i = 1000; i < 1000000000; i *= 10)
            {
                String testString = get_unique_string(i);
                Stopwatch stopwatch = new Stopwatch();
                MssqlTest test = new MssqlTest { TestId = DateTime.Now.ToString("dd.MM.yyyy hh:mm:ss:fff"), TestText = testString };

                stopwatch.Start();
                _mssqlContext.MssqlTests.Add(test);
                _mssqlContext.SaveChanges();
                stopwatch.Stop();

                outputTimes.Add(Encoding.UTF8.GetByteCount(testString), stopwatch.Elapsed);
            }
            return outputTimes;
        }

        string get_unique_string(int string_length)
        {
            using (var rng = new RNGCryptoServiceProvider())
            {
                var bit_count = (string_length * 6);
                var byte_count = ((bit_count + 7) / 8); // rounded up
                var bytes = new byte[byte_count];
                rng.GetBytes(bytes);
                return Convert.ToBase64String(bytes);
            }
        }
    }
}

WebKR_Schmelev/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebKR_Schmelev.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebKR_Schmelev/Pages/About.cshtml
@page
@model PrivacyModel
@{
	ViewData["Title"] = "About DBMS";
}
<h1>@ViewData["Title"]</h1>

<h2>PostgreSQL</h2>
<p>
	PostgreSQL — свободная объектно-реляционная система управления базами данных (СУБД).
	Существует в реализациях для множества UNIX-подобных платформ, включая AIX, различные BSD-системы, HP-UX, IRIX, Linux, macOS,
	Solaris/OpenSolaris, Tru64, QNX, а также для Microsoft Windows.
	PostgreSQL базируется на языке SQL и поддерживает многие из возможностей стандарта SQL:2011.
	В PostgreSQL версии 12 есть следующие ограничения:
</p>
<table class="table">

	<tbody>
	<tr>
		<td>Максимальный размер базы данных</td>
		<td>
			Нет ограничений
		</td>
	</tr>
	<tr>
		<td>Максимальный размер таблицы</td>
		<td>
			32 Тбайт
		</td>
	</tr>
	<tr>
		<td>Максимальный размер поля</td>
		<td>
			1 Гбайт
		</td>
	</tr>
	<tr>
		<td>Максимум записей в таблице</td>
		<td>
			Ограничено размерами таблицы
		</td>
	</tr>
	<tr>
		<td>Максимум полей в записи</td>
		<td>
			250—1600, в зависимости от типов полей
		</td>
	</tr>
	<tr>
		<td>Максимум индексов в таблице</td>
		<td>
			Нет ограничений
		</td>
	</tr>
	</tbody>
</table>
<p>
	Сильными сторонами PostgreSQL считаются:
</p>
<ul>
	<li>высокопроизводительные и надёжные механизмы репликации;</li>
	<li>высокопроизводительные и надёжные механизмы транзакций и репликации;</li>
	<li>расширяемая система встроенных языков программирования: в стандартной поставке поддерживаются PL/pgSQL, PL/Perl, PL/Python и PL/Tcl; дополнительно можно использовать PL/Java, PL/PHP, PL/Py, PL/R, PL/Ruby, PL/Scheme, PL/sh и PL/V8, а также имеется поддержка загрузки модулей расширения на языке C;</li>
	<li>наследование;</li>
	<li>возможность индексирования геометрических (в частности, географических) объектов и наличие базирующегося на ней расширения PostGIS;</li>
	<li>встроенная поддержка слабоструктурированных данных в формате JSON с возможностью их индексации;</li>
</ul>

<h2>Microsoft SQL Server</h2>
<p>
	Microsoft SQL Server — система управления реляционными базами данных (РСУБД), разработанная корпорацией Microsoft. 
	Основной используемый язык запросов — Transact-SQL, создан совместно Microsoft и Sybase. Transact-SQL является реализацией 
	стандарта ANSI/ISO по структурированному языку запросов (SQL) с расширениями. Используется для работы с базами данных размером 
	от персональных до крупных баз данных масштаба предприятия; конкурирует с другими СУБД в этом сегменте рынка.
</p>
<p>
	Microsoft SQL Server в качестве языка запросов использует версию SQL, получившую название Transact-SQL (сокращённо T-SQL), 
	являющуюся реализацией SQL-92 (стандарт ISO для SQL) с множественными расширениями. T-SQL позволяет использовать дополнительный 
	синтаксис для хранимых процедур и обеспечивает поддержку транзакций (взаимодействие базы данных с управляющим приложением). 
	Microsoft SQL Server и Sybase ASE для взаимодействия с сетью используют протокол уровня приложения под названием Tabular Data 
	Stream (TDS, протокол передачи табличных данных). Протокол TDS также был реализован в проекте FreeTDS с целью обеспечить 
	различным приложениям возможность взаимодействия с базами данных Microsoft SQL Server и Sybase.
</p>
<p>
	В SQL Server 2005 встроена поддержка .NET Framework. Благодаря этому, хранимые процедуры БД могут быть написаны на любом 
	языке платформы .NET, используя полный набор библиотек, доступных для .NET Framework, включая Common Type System (система 
	обращения с типами данных в Microsoft .NET Framework). Однако, в отличие от других процессов, .NET Framework, будучи базисной 
	системой для SQL Server 2005, выделяет дополнительную память и выстраивает средства управления SQL Server вместо того, чтобы 
	использовать встроенные средства Windows. Это повышает производительность в сравнении с общими алгоритмами Windows, так как 
	алгоритмы распределения ресурсов специально настроены для использования в структурах SQL Server.
</p>

<h2>Сравнение PostgreSQL vs. MSSQL</h2>
<table class="table">
<tbody>
<tr>
	<th>
		<p>
			<strong>Data type</strong>
		</p>
	</th>
	<th>
		<p>
			<strong>PostgreSQL</strong>
		</p>
	</th>
	<th>
		<p>
			<strong>SQL Server</strong>
		</p>
	</th>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>64-bit integer</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>BIGINT</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>BIGINT</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Fixed length byte string</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>BYTEA</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>BINARY(n)</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>1, 0 or NULL</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>BOOLEAN</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>BIT</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Fixed length char string, 1 &lt;= n &lt;= 8000</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>CHAR(n)</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>CHAR(n)</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Variable length char string, 1 &lt;= n &lt;= 8000</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>VARCHAR(n)</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>VARCHAR(n)</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Variable length char string, &lt;= 2GB</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>TEXT</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>VARCHAR(max)</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Variable length byte string , 1 &lt;= n &lt;= 8000</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>BYTEA</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>VARBINARY(n)</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Variable length byte string , &lt;= 2GB</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>BYTEA</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>VARBINARY(max)</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Variable length Unicode UCS-2 string</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>VARCHAR(n)</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>NVARCHAR(n)</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Variable length Unicode UCS-2 data, &lt;= 2GB</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>TEXT</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>NVARCHAR(max)</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Variable length character data, &lt;= 2GB</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>TEXT</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>TEXT</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Variable length Unicode UCS-2 data, &lt;= 2GB</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>TEXT</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>NTEXT</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Double precision floating point number</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>DOUBLE PRECISION</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>DOUBLE PRECISION</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Floating point number</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>DOUBLE PRECISION</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>FLOAT(p)</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>32 bit integer</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>INTEGER</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>INTEGER</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Fixed point number</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>NUMERIC(p,s)</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>NUMERIC(p,s)</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Date includes year, month, and day</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>DATE</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>DATE</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Date and time with fractional seconds</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>TIMESTAMP(p)</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>DATETIME, DATETIME2(p)</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Date and time with time zone</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>TIMESTAMP(p) WITH TIME ZONE</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>DATETIMEOFFSET(p)</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Date and time</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>TIMESTAMP(0)</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>SMALLDATETIME</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Unsigned integer, 0 to 255 (8 bit)</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>SMALLINT</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>TINYINT</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>UUID (16 byte)</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>CHAR(16)</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>UNIQUEIDENTIFIER</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Automatically updated binary data</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>BYTEA</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>ROWVERSION</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Currency amount (32 bit)</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>MONEY</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>SMALLMONEY</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Variable length binary data, &lt;= 2GB</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>BYTEA</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>IMAGE</strong>
		</p>
	</td>
</tr>
<tr>
	<td valign="top">
		<p>
			<strong>
				<strong>Geometric types</strong>
			</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>POINT, LINE, LSEG, BOX, PATH, POLYGON, CIRCLE</strong>
		</p>
	</td>
	<td valign="top">
		<p>
			<strong>GEOMETRY</strong>
		</p>
	</td>
</tr>
</tbody>
</table>

WebKR_Schmelev/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Тест";
}

<div class="text-center">
	<h1 class="display-4 mb-5">ТЕСТИРОВАНИЕ</h1>
	<form method="POST" class="mb-3">
		<input type="submit" class="btn btn-primary" asp-page-handler="ExecuteTest" value="Начать тест"></input>
	</form>
	@if (Model.TimesPostgres != null)
	{
		<h2 class="display-4 mb-3">Результаты тестирования</h2>
		<table class="table table-striped thead-dark table-bordered">
			<tr>
				<th>Размер поля, байт</th>
				<th>Время PostgreSQL</th>
				<th>Время MS SQL Server</th>
			</tr>
			<tbody>

				@for (int i = 0; i < Model.TimesPostgres.Count; i++)
				{
					<tr>
						<td>@Model.TimesPostgres.ElementAt(i).Key</td>
						<td>@Model.TimesPostgres.ElementAt(i).Value</td>
						<td>@Model.TimesMSSql.ElementAt(i).Value</td>
					</tr>
				}
			</tbody>

		</table>
	}
</div>

WebKR_Schmelev/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Тестирование СУБД</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="bg-light">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3 ">
            <div class="container">
				<a class="navbar-brand" asp-area="" asp-page="/Index">Тестирование СУБД</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-page="/Index">Тест</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-page="/About">СУБД</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container">
            &copy; Северин Д. В. гр.220681  - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>